---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Parameters:
  EC2InstanceType:
    Default: t2.micro
    Description: EC2 instance type
    Type: String
  SubnetId:
    Description: Target subnet for instance
    Type: AWS::EC2::Subnet::Id

Resources:
  ManagementStation:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 20
      Description: 
        Fn::Sub ${AWS::StackName} Station
      InstanceType: !Ref EC2InstanceType
      Name: !Sub ${AWS::StackName}-station
      SubnetId:
        Ref: SubnetId